### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shierru** [Southclaws/pawn-parser#2]
I was researching commits in the main branch and came across the first changes in it. I understand you wanted to take the libraries as a basis and adapt them to Pawn?
Why did you decide not to do that? You decided to make an implementation from scratch, taking almost nothing as a basis.

**Comment by Southclaws** [comment]
At first I figured Go and Pawn are similar enough in syntactical design to re-use the tokeniser but then realised that Pawn has a lot of complexities due to macros. I was going to construct a pluggable tokeniser that you could easily add AST pipelines to handle things like `foreach` and `hook` from YSI but realised this was too much work. I should archive/delete the repo since it's not really useful.
